### ISSUE TITLE
Load Domain Cookies

### ISSUE THREAD

**Issue by eduardoestevao** [CookieCadger/CookieCadger#11]
Hi, i don't know whats the real cause...but cookie cadger 1.06 can't open the browser here...i was on firefox 16 and now updated to version 22 and nothing, cookie cadger captures normally, when i click on "load domain cookies" or load session opens the box saying "Load request into browser, please wait..." but over 30 min, nothing happend.. any way i could find out the problem? like some log?

Ps: Windows 7 64bits
Thanks in advance.

**Comment by sullivanmatt** [comment]
Is this issue still occurring for you?  I am unable to reproduce it.
