### ISSUE TITLE
Facebook login notifications

### ISSUE THREAD

**Issue by bl-tie2** [CookieCadger/CookieCadger#12]
Hi, I'm just wondering whether someone who has facebook's login notification enabled would get a notification when a CookieCadger user used a "grabbed" cookie or replayed a request in a browser?

On one hand, I guess the original GET request is after authentication so you'd assume "NO", but on the other hand, if it's seen as a "new browser" (as facebook call it), then it's "YES".

Look forward to your response.

**Comment by computmaxer** [comment]
No, they would not get a notification.
That all happens during the session negotiation at login, when the session cookie is created and given to the browser.  All activity after that with the same session cookie will be treated like the same session, even if the User-Agent changes.

Facebook theoretically could detect a change in the User-Agent string relative to a session cookie, but they do not.  That is not really a common practice as far as I know.

**Comment by computmaxer** [comment]
Also, CookieCadger already takes the UserAgent string from the victim's request and injects it into the browser when replaying the session cookie.  So websites like Facebook will not actually see the request as coming from a "new browser".
