### ISSUE TITLE
No session data & monitor mode issues

### ISSUE THREAD

**Issue by Thorsen31** [CookieCadger/CookieCadger#13]
Hi everyone,
I'me having a hard time trying to figure out why CookieCadger and Wireshark seem to behave strangely on my Macbook Pro (Mac OS X.8.4, using my en1 wifi card). I've been looking for answers for hours now.

I installed XQuartz and Wireshark 1.10.1, which is able to get HTTP packets only when i'm not turned in monitor mode (but promiscuous is on), otherwise I only get broadcast stuff (uncolored).
Concerning CookieCadger, I'm able to listen to my own computer (but I can't see my smartphone's activity for example) and the requests I can get do not allow me to reproduce any session i closed. Furthermore, the "Recognized Session" display remains empty.

My issues seem so ridiculous there must be something really big behind...
I hope I'm clear enough and I'm sorry to bother with such nooby stuff.

Thorsen31.
P.S :I can add screenshots if it helps.

**Comment by Thorsen31** [comment]
EDIT : I read in a previous post that CookieCadger is not made to work on a WPA2 encrypted wifi, could it be the cause of my issues ?

**Comment by mpdavis** [comment]
If you network is encrypted with WPA2, you will not be able to see traffic from other devices (which is why you should be using WPA2 on any network you control.)  

If you want to play around with CookieCadger, you will have to turn all encryption off on your wireless network.

**Comment by Thorsen31** [comment]
Hi,

Thank you very much for such a quick answer. It's reassuring in a way.
Now, what if I decide to plug my computer on the same network using an ethernet cable. Will the traffic from devices using the WPA2 encrypted wifi be visible ? In other words, is the security that provides WPA2 still efficient when someone has a physical access to the local network ?

Thank's a lot again !
Thorsen31

**Comment by sullivanmatt** [comment]
Networks try to be sensitive about who they send data to.  If you plug in via Ethernet, you still won't see the Wi-Fi traffic because you'll likely be plugged into a switch, which will not send that traffic down your cable if you don't need to be receiving it.  In that situation you'd have to perform something like ARP Spoofing, which is outside the realm of what Cookie Cadger can do.  Closing this issue, but you can continue to comment if you seek further clarification.  Thanks!
