### ISSUE TITLE
Cookie Cadger will only show traffic from the computer it was launched on

### ISSUE THREAD

**Issue by Rick-LWD** [CookieCadger/CookieCadger#14]
I can't seem to get access to any traffic from any other computer on my wireless and unsecured network. Has anyone else had this problem?

**Comment by computmaxer** [comment]
It sounds like you have not put your wireless card in monitor mode/promiscuous mode.  CookieCadger does not do that for you.

**Comment by Rick-LWD** [comment]
Thanks for answering! What would be the easiest way to put it into monitor mode though?

EDIT: I would really appreciate an answer to this, because Google isn't helping me much.

**Comment by computmaxer** [comment]
What operating system are you using and do you know the manufacturer of your wireless card?

**Comment by Rick-LWD** [comment]
Windows 7 and Broadcom

**Comment by sullivanmatt** [comment]
Windows can't natively perform monitor mode without some specialized hardware and/or drivers.  You'll likely find this easiest to do if you are using Linux.

I'm going to close this ticket because it's an issue outside of Cookie Cadger, but please feel free to continue this discussion.

**Comment by Rick-LWD** [comment]
Ok, thanks Matt. That's basically what I came here to find out I guess. Would it be easiest to buy some extra hardware (and if so, what should I buy) or are there special drivers I can download which won't make that necessary? I'm willing to spend some money on extra hardware if it makes the process easier.

I appreciate all the help.

**Comment by benjholla** [comment]
This is what I use.  You can find these dirt cheap if you keep searching,
the one I linked below is more expensive than most.  Most linux installs
including Backtrack have the drivers already installed, so if you use
VMWare player or virtual box or something you can just plug it in and go.

http://www.amazon.com/Alfa-Wireless-Original-Screw-On-9dBi/dp/B001O9X9EU

~Ben

**Comment by Rick-LWD** [comment]
Ok, so I will buy what you just linked me to and install VMWare player to work with it?

See I never really found info like this on Google. Maybe some future searches will end up here. 
Thanks guys.

**Comment by sullivanmatt** [comment]
I actually use Windows full-time and run a Linux VM like benjholla is suggesting.  You'd buy that, then start your VM and 'pass through' the USB device (like with this screenshot: https://communities.vmware.com/servlet/JiveServlet/download/1553921-39801/Devices.jpg).  Then tell the aircrack suite to put your interface in monitor mode with: sudo airmon-ng start wlan0 X  (where X is the 2.4GHz channel to monitor).

**Comment by benjholla** [comment]
Looking at my order history, this actually the one I had bought (I think it
was more like 20 dollars back in 2011).  The Alpha cards have a particular
notoriety in the hacker community for wifi hacking.  Your looking for
anything with the "Realtek 8187L" chipset, there are other chipsets
but the Realtek
8187 chipset is well supported and cheap.  That chipset is able to do
packet inject as well, so you can do other hacks with it (like cracking
wifi networks).  You'll see this card and other's with the same chipset
repackaged in a ton of different brands.  I had a friend order from China
off Deal Extreme once and get something similar to this one (link below).
 Just a note, the cheap cards come with crappy drivers, you don't need
those so don't install them.  Just use the drivers in the linux packages
bundled with Backtrack or whatever distro you go with.  Using a security
linux distro will also have all the other tools ready to go.

Chinese version:
http://dx.com/p/9800000g-3000mw-802-11b-g-54mbps-usb-2-0-wifi-wireless-network-adapter-115930

One I bought from Amazon:
http://www.amazon.com/gp/product/B002WCEWU8/ref=oh_details_o07_s01_i01?ie=UTF8&psc=1

Same thing with a cool antenna:
http://www.amazon.com/Alfa-AWUS036H-Upgraded-Long-Rang-Panel/dp/B003YHYIT0/ref=pd_cp_pc_2

For more resources you can google around a little more.  Here's another
article that has some details.
http://www.raymond.cc/blog/best-compatible-usb-wireless-adapter-for-backtrack-5-and-aircrack-ng/

~Ben
