### ISSUE TITLE
Matt, my domain cookies won't load

### ISSUE THREAD

**Issue by SacredBlue** [CookieCadger/CookieCadger#16]
Matt, my domain cookies won't load.  I am on a MacBookAir using Safari as a browser.    Is it due to the security on my MacBook or the browser?

**Comment by sullivanmatt** [comment]
If you select an individual request and hit "Replay Request", does that work?

To get a complete list of errors while running the software, try running it from command-line with: java -jar CookieCadger-XXX.jar (where the XXX are the version you are running).

**Comment by sullivanmatt** [comment]
Also Cookie Cadger requires Firefox to be installed and running the latest version.

**Comment by SacredBlue** [comment]
Matt,

That did not work - it just never loads.  Is it the Safari browser maybe?
 I have seen a few other people have had this problem.

**Comment by computmaxer** [comment]
Cookie Cadger does not support the Safari browser.  You will need to download Firefox for it to work.

**Comment by SacredBlue** [comment]
Still not working with FireFox.  Also, Matt, can you recommended any free
software for Facebook password?

**Comment by sullivanmatt** [comment]
What do you mean by "free software for Facebook password"?

**Comment by SacredBlue** [comment]
Can Cookie Cadger see the password to someone else's Facebook when they are
on same network?

**Comment by benjholla** [comment]
Cookie Cadger grabs sessions not passwords.  Facebook uses SSL now, so
unless you somehow decrypt the stream you won't be catching any passwords.
 If it were unencrypted network traffic you could parse through Wireshark
PCAP and try to find it.  That's not what Cookie Cadger is designed to do
though.

**Comment by benjholla** [comment]
We are going to need more information to help you with Cookie Cadger.  

1) What version of Firefox are you using
2) What is the output of Cookie Cadger when running it from the command line with: java -jar CookieCadger-XXX.jar (where the XXX are the version you are running).

**Comment by benjholla** [comment]
Closing this issue because there is nothing to diagnose.  Feel free to reopen the issue if you have a stack trace or more detailed error information.

**Comment by skaitlin** [comment]
My firefox keeps popping up when I press load but it stays blank and then closes. Help?
