### ISSUE TITLE
Coockier cadger does not work! When I start the cookie stops at 0 seconds Sorry i dont speak english! 

### ISSUE THREAD

**Issue by LALOMARS** [CookieCadger/CookieCadger#17]
this is what it says

tshark located at C:\Program Files\Wireshark\tshark.exe
Querying tshark for capture devices; tshark output follows:
1. \Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F} (ConexiÃ³n de red inalÃ¡mbrica)
Capture device search completed with 1 devices found.

Cookie Cadger (v1.06, https://cookiecadger.com)
Created by Matthew Sullivan - mattslifebytes.com
This software is freely distributed under the terms of the FreeBSD license.

Opening '\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}' for traffic capture.
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: ============================================================================
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: Start of diagnostic information for interface '\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}'
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: ============================================================================
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: ============================================================================
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: Potential error detected! Capture stopped / died in 0 seconds.
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: All messages from the 'tshark' program have been printed above to assist you in solving any errors.
\Device\NPF_{3C5E56EC-104B-4D5D-8708-A8F1CBA80D1F}: 

plis helpme i dont have Network Card! i have a wireless network adapter! 
and Wireshark does not work, only un-checking the "Promiscuous mode" checkbox in the "Capture options" dialog box.

**Comment by sullivanmatt** [comment]
You are attempting to capture on a Windows virtual device in the above capture.  You can see which devices are more likely candidates for capturing from inside of Wireshark.  Windows has no ability to place a wireless network card in monitor mode; if you wish to capture local wireless traffic you'll have to use Linux.
