### ISSUE TITLE
No privacy policy

### ISSUE THREAD

**Issue by zD12** [CookieCadger/CookieCadger#22]
You're lacking of a Privacy Policy on https://www.cookiecadger.com, please add ASAP

**Comment by sullivanmatt** [comment]
I can add one, but it will be pretty generic.  I will cover what data is collected, though.  Do you have any specific concerns?

**Comment by sullivanmatt** [comment]
A link to the privacy policy is now available at the bottom of each page:
https://www.cookiecadger.com/?page_id=193
