### ISSUE TITLE
Doesn't work with newer Firefox versions

### ISSUE THREAD

**Issue by dmarkow** [CookieCadger/CookieCadger#23]
It looks like there might be another selenium server upgrade necessary (current version is 2.43.1, this project uses 2.40.0). Tried with Firefox 33 and was getting this problem when trying to load a session:

```
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
```

Downgraded to Firefox 26 and it worked fine.

**Comment by dmarkow** [comment]
Works great with Firefox 33! Thanks for the super-quick turnaround on this.

**Comment by sullivanmatt** [comment]
Happy to help - let me know if you encounter issues in the future!
