### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by L1ghtn1ng** [CookieCadger/CookieCadger#4]
would be awesome if you could get your awesome tool in kali linux

**Comment by computmaxer** [comment]
+1

**Comment by sullivanmatt** [comment]
Someone else has already requested.  http://bugs.kali.org/view.php?id=269

**Comment by sullivanmatt** [comment]
I have added to the post in support and set myself as a watcher on the issue.  If it doesn't go anywhere in a couple of months I'll try to holler at them.
