### ISSUE TITLE
Cookie Cadger doesnt work for me at all

### ISSUE THREAD

**Issue by Shredda1337** [CookieCadger/CookieCadger#7]
Hey guys... 

Im using wireshark 1.8.0 - using Cookie Cadger 1.0 and Windows 7... I really cant use Cookie Cadger and dont know why... I tried everything but it doesnt even show any recoginzed sessions for me, never - it doesnt even Load domains or something... what am I doing wrong?

kind regards, 

Pat

**Comment by Shredda1337** [comment]
btw im using Java 7

**Comment by computmaxer** [comment]
What kind of connection are you monitoring?  If it's wireless, what kind of security does it have?  A common problem that people have is trying it on a WPA encrypted network which will not work.

Including screenshots would help us help you as well.

**Comment by Shredda1337** [comment]
I will do this tomorrow and give you a view of my router stuff or infos about this. Im using WPA2 for my wireless network. What should I use instead? I actually dont know if there is a firewall included... but i think so...

**Comment by computmaxer** [comment]
CookieCadger can only make use of traffic that is can see.  WPA2 doesn't allow for this.

**Comment by Shredda1337** [comment]
So which security should i use then? Which one allows it?

**Comment by mpdavis** [comment]
If you don't want people on your network to use tools like CookieCadger, you should continue to use WPA2.  If you are looking to play around with CookieCadger, just turn all encryption off.
