### ISSUE TITLE
Session Capture/Loading Domain Cookies

### ISSUE THREAD

**Issue by Caleb253** [CookieCadger/CookieCadger#8]
Ok so im still a little new at this and it all seem pretty straight foward, but let me get this cleared out of the air.

Sites like Yahoo/Facebook/Twitter/GMail use Https:// Protocols, with that being said, is Cookie Cadger able to view these pages with the potential of interaction? i.e. (and excuse me for being frank) taking the PW cookie and applying it to the site to reward access?

like i said im new and just playing around at the local starbucks but would like to know how to enable the full potential.

**Comment by computmaxer** [comment]
No, this only works on unencrypted traffic that you can eavesdrop on.  HTTPS provides end-to-end encryption to prevent an attack such as the one CookieCadger performs.

**Comment by Caleb253** [comment]
hmm so how does one view a Facebook Profile or interact with one with out knowing the passwprd? A friend of mine just had theirs hacked and was wondering how in the hell it was possible.

**Comment by benjholla** [comment]
If your friend was browsing on an unencrypted network and the site was not using HTTPS, then the session secret key can be captured with CookieCadger and your friends account session would be stolen.  Note that if you have a valid session, you don't need the account password.  It's similar to if your friend forgot to logout out of Facebook on a public computer and a stranger sat down and found the logged in account.

~Benjamin Holland
